apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    aliyun.routing.port_3000: http://rails_demo
    aliyun.scale: "3"
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - rails
        - s
        - -b
        - "0:0:0:0"
        image: simonsu99/rails_app:v1.0.0
        name: web
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
